beta: true
language: en
BetaSpawn:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0

LobbySpawn:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0

keys:
  open:
  player:
  time:

# You need to install LuckPerms for this feature to work
luckperms:
  player_group: default   # Edit this to the group you want the player to join after a registration